/*
Run audit report
*/

SELECT AUDIT_EVENT.EVENT_ID,
AUDIT_EVENT.USER_NAME,
AUDIT_EVENT.START_TIMESTAMP,
AUDIT_EVENT.DURATION,
DETAIL_TYPE.DETAIL_TYPE_DESCRIPTION,
SERVER_PROCESS.Server_Name,
SERVER_PROCESS.SERVER_FULLNAME,
AUDIT_EVENT.ERROR_CODE,
AUDIT_DETAIL.DETAIL_TEXT,
EVENT_TYPE.EVENT_TYPE_DESCRIPTION
FROM
AUDIT_EVENT,
DETAIL_TYPE,
SERVER_PROCESS,
AUDIT_DETAIL,
EVENT_TYPE
WHERE ( AUDIT_EVENT.EVENT_ID=AUDIT_DETAIL.EVENT_ID ) AND ( AUDIT_EVENT.SERVER_CUID=SERVER_PROCESS.SERVER_CUID ) AND ( AUDIT_EVENT.EVENT_TYPE_ID=EVENT_TYPE.EVENT_TYPE_ID ) AND ( AUDIT_DETAIL.DETAIL_TYPE_ID=DETAIL_TYPE.DETAIL_TYPE_ID )
